--CREATE TABLE tbl_users (
--	id SERIAL,
--	email VARCHAR(50) NOT NULL,
--	username VARCHAR(50) NOT NULL,
--	password VARCHAR(255) NOT NULL,
--	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	UNIQUE(username),
--	PRIMARY KEY(id)
--);
--INSERT INTO tbl_users (email, username, password) VALUES
--('sysadmin@email.com', 'sysadmin', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6'),
--('admin@email.com', 'admin', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6'),
--('manager@email.com', 'manager', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6'),
--('user@email.com', 'user', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6'),
--('other@email.com', 'other', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6');