package com.sample.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.sample.model.nestedObject.Address;
import com.sample.utils.UserStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

import static com.sample.utils.Constant.REGEX.DD_M_YYYY_HH_MM_SS;
import static com.sample.utils.Constant.REGEX.YYYY_MM_DD_HH_MM_SS;
import static com.sample.utils.Constant.INDEX.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "sample_user")
public class SampleUser {

    @DynamoDBHashKey
    @DynamoDBIndexHashKey(globalSecondaryIndexNames = {FIRST_NAME})
    private String hashKey;
    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    private String rangeKey;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = FIRST_NAME)
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = PHONE)
    private String phone;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = EMAIL)
    private String email;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.M)
    private Address address;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private UserStatus status;

    @DynamoDBAttribute
    private String searchKeys;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private Boolean isFirstLogin;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp(pattern = DD_M_YYYY_HH_MM_SS, timeZone = "GTM")
    private Date createdAt;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp(pattern = YYYY_MM_DD_HH_MM_SS, timeZone = "UTC")
    private Date updatedAt;
}
